services:
  - type: web
    name: localloop-backend-jeand157
    env: node
    plan: free # Vous pouvez changer pour un plan payant si n√©cessaire
    buildCommand: npm install && npm run build -w apps/backend
    startCommand: npm run start -w apps/backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DB_HOST
        value: yamabiko.proxy.rlwy.net
      - key: DB_PORT
        value: "14050"
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: qvsdcudxJsCVbSFbdYHrvjlDgioobDBs
      - key: DB_NAME
        value: railway
      - key: FRONTEND_URL
        value: https://devforge-frontend.vercel.app
